import { useEffect, useMemo, useState } from 'react';
import { api } from '../api.js';

const dateKey = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Karachi' }).format(new Date());

function useResource(endpoint) {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  async function load() { setLoading(true); try { const r = await api.get(endpoint); setItems(r.data.data); setError(''); } catch (e) { setError(e.response?.data?.message || 'Could not load records'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [endpoint]);
  async function create(data) { await api.post(endpoint, data); await load(); }
  async function update(id, data) { await api.patch(`${endpoint}/${id}`, data); await load(); }
  async function remove(id) { await api.delete(`${endpoint}/${id}`); await load(); }
  return { items, loading, error, create, update, remove, reload: load };
}

function PageHeader({ eyebrow, title, description, children }) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p className="muted">{description}</p></div>{children}</div>; }
function Empty({ children }) { return <div className="empty"><span className="eyebrow">NOTHING HERE YET</span><p className="muted">{children}</p></div>; }
function ErrorMessage({ error }) { return error ? <p className="error">{error}</p> : null; }

export function Dashboard() {
  const tasks = useResource('/tasks'), goals = useResource('/goals'), habits = useResource('/habits'), timetable = useResource('/timetable');
  const today = dateKey(); const todayEvents = timetable.items.filter(x => x.dateKey === today); const doneTasks = tasks.items.filter(x => x.status === 'COMPLETED').length; const activeGoals = goals.items.filter(x => x.status === 'ACTIVE');
  return <div><div className="hero"><div><span className="eyebrow">TODAY’S COMMAND CENTER</span><h1>Make the day count.</h1><p className="muted">Your plan becomes useful when it becomes a record.</p></div><a className="button" href="/app/tasks">+ Add a task</a></div><div className="grid"><Card label="PRODUCTIVITY" value="—" detail="Historical score arrives after review" /><Card label="TASKS" value={`${doneTasks} / ${tasks.items.length}`} detail="Completed tasks" /><Card label="HABITS" value={habits.items.length} detail="Active routines" /><Card label="TIMETABLE" value={todayEvents.length} detail="Events planned today" /></div><div className="dashboard-columns"><section className="panel"><span className="eyebrow">TODAY’S PLAN</span>{tasks.loading ? <p className="muted">Loading…</p> : tasks.items.slice(0, 5).map(task => <div className="mini-row" key={task._id}><span className={`dot ${task.status === 'COMPLETED' ? 'green' : ''}`} /><span>{task.title}</span><small>{task.status.replace('_', ' ')}</small></div>)}{!tasks.loading && !tasks.items.length && <Empty>Add your first task to start shaping the day.</Empty>}</section><section className="panel"><span className="eyebrow">ACTIVE GOALS</span>{activeGoals.slice(0, 4).map(goal => <div className="goal-row" key={goal._id}><div><strong>{goal.title}</strong><small>{goal.currentProgress || 0} / {goal.target || 0} {goal.unit || ''}</small></div><div className="progress"><span style={{ width: `${Math.min(100, ((goal.currentProgress || 0) / (goal.target || 1)) * 100)}%` }} /></div></div>)}{!activeGoals.length && <Empty>Create a measurable goal for your next milestone.</Empty>}</section></div></div>;
}
function Card({ label, value, detail }) { return <div className="card"><span className="eyebrow">{label}</span><strong>{value}</strong><p className="muted">{detail}</p></div>; }

export function TasksPage() { const resource = useResource('/tasks'); const [form, setForm] = useState({ title: '', priority: 'MEDIUM', dueDateKey: dateKey() }); async function add(e) { e.preventDefault(); if (!form.title.trim()) return; await resource.create(form); setForm({ ...form, title: '' }); } return <div><PageHeader eyebrow="EXECUTE" title="Tasks" description="Turn intentions into visible, finishable work." /><section className="panel form-panel"><form className="inline-form" onSubmit={add}><input placeholder="What needs to be done?" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /><select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select><input type="date" value={form.dueDateKey} onChange={e => setForm({ ...form, dueDateKey: e.target.value })} /><button>Add task</button></form></section><ErrorMessage error={resource.error} /><section className="list">{resource.loading ? <p className="muted">Loading tasks…</p> : resource.items.map(task => <div className={`list-row ${task.status === 'COMPLETED' ? 'is-done' : ''}`} key={task._id}><button className="check" onClick={() => resource.update(task._id, { status: task.status === 'COMPLETED' ? 'TODO' : 'COMPLETED', completedAt: task.status === 'COMPLETED' ? null : new Date() })}>{task.status === 'COMPLETED' ? '✓' : ''}</button><div className="row-main"><strong>{task.title}</strong><small>{task.priority} · Due {task.dueDateKey || '—'}</small></div><button className="icon-button" onClick={() => resource.remove(task._id)}>Delete</button></div>)}{!resource.loading && !resource.items.length && <Empty>Capture the first concrete action for today.</Empty>}</section></div>; }

export function GoalsPage() { const resource = useResource('/goals'); const [form, setForm] = useState({ title: '', target: 100, currentProgress: 0, unit: '%', deadlineKey: '' }); async function add(e) { e.preventDefault(); if (!form.title.trim()) return; await resource.create({ ...form, target: Number(form.target), currentProgress: Number(form.currentProgress) }); setForm({ ...form, title: '' }); } return <div><PageHeader eyebrow="DIRECTION" title="Goals" description="Make progress measurable without losing the bigger picture." /><section className="panel form-panel"><form className="grid-form" onSubmit={add}><input placeholder="Goal title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /><input type="number" placeholder="Target" value={form.target} onChange={e => setForm({ ...form, target: e.target.value })} /><input placeholder="Unit, e.g. hours" value={form.unit} onChange={e => setForm({ ...form, unit: e.target.value })} /><input type="date" value={form.deadlineKey} onChange={e => setForm({ ...form, deadlineKey: e.target.value })} /><button>Add goal</button></form></section><section className="goal-grid">{resource.items.map(goal => { const pct = Math.min(100, Math.round(((goal.currentProgress || 0) / (goal.target || 1)) * 100)); return <div className="panel goal-card" key={goal._id}><div className="row-between"><span className="eyebrow">{goal.status}</span><button className="icon-button" onClick={() => resource.remove(goal._id)}>Delete</button></div><h3>{goal.title}</h3><strong>{pct}%</strong><div className="progress"><span style={{ width: `${pct}%` }} /></div><p className="muted">{goal.currentProgress || 0} / {goal.target || 0} {goal.unit || ''}{goal.deadlineKey && ` · due ${goal.deadlineKey}`}</p></div> })}{!resource.loading && !resource.items.length && <Empty>Choose one outcome that would make the next season meaningful.</Empty>}</section></div>; }

export function HabitsPage() { const resource = useResource('/habits'); const [form, setForm] = useState({ title: '', dailyTarget: 30, targetUnit: 'minutes', minimumAcceptable: 10, preferredTime: '20:00' }); async function add(e) { e.preventDefault(); if (!form.title.trim()) return; await resource.create({ ...form, dailyTarget: Number(form.dailyTarget), minimumAcceptable: Number(form.minimumAcceptable), planStartDateKey: dateKey(), status: 'ACTIVE' }); setForm({ ...form, title: '' }); } async function log(habit) { const actual = window.prompt(`Actual ${habit.targetUnit || 'value'} for ${habit.title}?`, String(habit.dailyTarget || 0)); if (actual === null) return; await api.post(`/habits/${habit._id}/log`, { dateKey: dateKey(), actualValue: Number(actual) }); await resource.reload(); } return <div><PageHeader eyebrow="CONSISTENCY" title="Habits" description="Build plans that are forgiving enough to survive real life." /><section className="panel form-panel"><form className="grid-form" onSubmit={add}><input placeholder="Habit name" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /><input type="number" placeholder="Daily target" value={form.dailyTarget} onChange={e => setForm({ ...form, dailyTarget: e.target.value })} /><input placeholder="Unit" value={form.targetUnit} onChange={e => setForm({ ...form, targetUnit: e.target.value })} /><input type="time" value={form.preferredTime} onChange={e => setForm({ ...form, preferredTime: e.target.value })} /><button>Start habit</button></form></section><section className="list">{resource.items.map(habit => <div className="list-row" key={habit._id}><div className="habit-mark">↻</div><div className="row-main"><strong>{habit.title}</strong><small>{habit.dailyTarget} {habit.targetUnit} daily · minimum {habit.minimumAcceptable} · {habit.preferredTime}</small></div><button className="secondary" onClick={() => log(habit)}>Log today</button><button className="icon-button" onClick={() => resource.remove(habit._id)}>Delete</button></div>)}{!resource.loading && !resource.items.length && <Empty>Start one habit with a clear target and preferred time.</Empty>}</section></div>; }

export function TimetablePage() { const resource = useResource('/timetable'); const [form, setForm] = useState({ title: '', dateKey: dateKey(), startTime: '09:00', endTime: '10:00', category: 'Focus' }); async function add(e) { e.preventDefault(); if (!form.title.trim()) return; await resource.create(form); setForm({ ...form, title: '' }); } return <div><PageHeader eyebrow="FOLLOW THE PLAN" title="Timetable" description="Give important work a place to happen." /><section className="panel form-panel"><form className="grid-form" onSubmit={add}><input placeholder="Activity" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /><input type="date" value={form.dateKey} onChange={e => setForm({ ...form, dateKey: e.target.value })} /><input type="time" value={form.startTime} onChange={e => setForm({ ...form, startTime: e.target.value })} /><input type="time" value={form.endTime} onChange={e => setForm({ ...form, endTime: e.target.value })} /><button>Add event</button></form></section><section className="list">{resource.items.map(event => <div className="list-row" key={event._id}><div className="time-mark">{event.startTime}</div><div className="row-main"><strong>{event.title}</strong><small>{event.dateKey} · {event.startTime}–{event.endTime} · {event.category}</small></div><button className="icon-button" onClick={() => resource.remove(event._id)}>Delete</button></div>)}{!resource.loading && !resource.items.length && <Empty>Schedule the first block you want to protect today.</Empty>}</section></div>; }

export function PlaceholderPage({ title }) { return <div><PageHeader eyebrow="COMING NEXT" title={title} description="This module is part of the next expansion of your Life OS." /><div className="panel"><Empty>Core planning is ready. This area will be connected to analytics and historical reviews next.</Empty></div></div>; }
