import { z } from 'zod';

const dateKey = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Use YYYY-MM-DD');
const positive = z.coerce.number().min(0, 'Must be zero or greater');
export const registerSchema = z.object({ name: z.string().trim().min(2).max(80), email: z.string().email(), password: z.string().min(8).max(128), timezone: z.string().trim().min(1).max(80).optional() });
export const loginSchema = z.object({ email: z.string().email(), password: z.string().min(1).max(128) });
export const phoneSchema = z.object({ dateKey, phoneUsageMinutes: positive, mood: z.coerce.number().int().min(1).max(5).optional(), energyLevel: z.coerce.number().int().min(1).max(5).optional(), sleepMinutes: positive.optional(), notes: z.string().max(1000).optional() });
export const expenseSchema = z.object({ type: z.enum(['EXPENSE', 'INCOME']).default('EXPENSE'), amount: z.coerce.number().positive(), category: z.string().trim().min(1).max(60), subcategory: z.string().max(60).optional(), paymentMethod: z.string().max(40).optional(), description: z.string().max(200).optional(), notes: z.string().max(1000).optional(), dateKey, occurredAt: z.coerce.date().optional(), isRecurring: z.boolean().optional() });
export const taskSchema = z.object({ title: z.string().trim().min(1).max(200), description: z.string().max(2000).optional(), priority: z.enum(['LOW', 'MEDIUM', 'HIGH']).optional(), status: z.enum(['TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DEFERRED']).optional(), dueDateKey: dateKey.optional(), estimatedMinutes: positive.optional(), actualMinutes: positive.optional(), category: z.string().max(60).optional(), tags: z.array(z.string().max(40)).max(20).optional() });
export const goalSchema = z.object({ title: z.string().trim().min(1).max(200), description: z.string().max(2000).optional(), category: z.string().max(60).optional(), target: positive.optional(), currentProgress: positive.optional(), unit: z.string().max(30).optional(), deadlineKey: dateKey.optional(), priority: z.string().max(20).optional(), status: z.enum(['ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED']).optional() });
export const habitSchema = z.object({ title: z.string().trim().min(1).max(160), description: z.string().max(1000).optional(), frequencyType: z.enum(['DAILY', 'WEEKLY', 'CUSTOM']).optional(), weekdays: z.array(z.number().int().min(0).max(6)).max(7).optional(), planStartDateKey: dateKey.optional(), planEndDateKey: dateKey.optional(), dailyTarget: positive.optional(), targetUnit: z.string().max(30).optional(), minimumAcceptable: positive.optional(), preferredTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'Use HH:mm').optional(), status: z.enum(['ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED']).optional() });
export const timetableSchema = z.object({ title: z.string().trim().min(1).max(160), category: z.string().max(60).optional(), dateKey, startTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), endTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), priority: z.string().max(20).optional(), color: z.string().max(20).optional(), notes: z.string().max(1000).optional(), status: z.enum(['PLANNED', 'COMPLETED', 'PARTIAL', 'MISSED']).optional() }).superRefine((value, ctx) => { if (value.endTime <= value.startTime) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['endTime'], message: 'End time must be after start time' }); });
export const timetableUpdateSchema = z.object({ title: z.string().trim().min(1).max(160).optional(), category: z.string().max(60).optional(), dateKey: dateKey.optional(), startTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional(), endTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional(), priority: z.string().max(20).optional(), color: z.string().max(20).optional(), notes: z.string().max(1000).optional(), status: z.enum(['PLANNED', 'COMPLETED', 'PARTIAL', 'MISSED']).optional() }).superRefine((value, ctx) => { if (value.startTime && value.endTime && value.endTime <= value.startTime) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['endTime'], message: 'End time must be after start time' }); });
export const exercisePlanSchema = z.object({ name: z.string().trim().min(1).max(160), description: z.string().max(1000).optional(), status: z.enum(['ACTIVE', 'ARCHIVED']).optional(), schedule: z.array(z.object({ weekday: z.number().int().min(0).max(6), exercises: z.array(z.object({ name: z.string().trim().min(1).max(100), muscleGroup: z.string().max(60).optional(), sets: positive.optional(), repetitions: positive.optional(), durationMinutes: positive.optional(), distance: positive.optional() })).max(30) })).max(7).optional() });
export const exerciseLogSchema = z.object({ planId: z.string().regex(/^[a-f\d]{24}$/i).optional(), dateKey, workoutType: z.string().trim().min(1).max(80), completed: z.boolean().default(true), notes: z.string().max(1000).optional(), exercises: z.array(z.object({ name: z.string().trim().min(1).max(100), sets: positive.optional(), repetitions: positive.optional(), weight: positive.optional(), durationMinutes: positive.optional(), distance: positive.optional(), calories: positive.optional() })).max(30).default([]) });
export const projectSchema = z.object({ name: z.string().trim().min(1).max(160), description: z.string().max(2000).optional(), status: z.enum(['PLANNED', 'ACTIVE', 'COMPLETED', 'PAUSED', 'ARCHIVED']).optional(), priority: z.enum(['LOW', 'MEDIUM', 'HIGH']).optional(), startDateKey: dateKey.optional(), deadlineKey: dateKey.optional(), tags: z.array(z.string().max(40)).max(20).optional() });
export const milestoneSchema = z.object({ title: z.string().trim().min(1).max(160), description: z.string().max(1000).optional(), dateKey: dateKey.optional(), completed: z.boolean().optional() });
export const habitLogSchema = z.object({ dateKey, actualValue: positive, notes: z.string().max(1000).optional() });
export const settingsSchema = z.object({ name: z.string().trim().min(2).max(80).optional(), timezone: z.string().trim().min(1).max(80).optional(), currency: z.string().trim().min(3).max(8).optional(), weekStartsOn: z.coerce.number().int().min(0).max(6).optional(), theme: z.enum(['dark', 'light', 'system']).optional(), phoneUsageRequired: z.boolean().optional(), spendingAccountabilityRequired: z.boolean().optional(), phoneTargetMinutes: positive.optional(), scoreWeights: z.record(z.coerce.number().min(0).max(100)).optional() });
